[2022-12-30T20:52:21.927-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: realtor_census_dashboard_etl.Extract_n_Transform_Data scheduled__2022-03-17T00:00:00+00:00 [queued]>
[2022-12-30T20:52:21.935-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: realtor_census_dashboard_etl.Extract_n_Transform_Data scheduled__2022-03-17T00:00:00+00:00 [queued]>
[2022-12-30T20:52:21.935-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-30T20:52:21.935-0500] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-30T20:52:21.935-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-30T20:52:21.943-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): Extract_n_Transform_Data> on 2022-03-17 00:00:00+00:00
[2022-12-30T20:52:21.947-0500] {standard_task_runner.py:55} INFO - Started process 24349 to run task
[2022-12-30T20:52:21.951-0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'realtor_census_dashboard_etl', 'Extract_n_Transform_Data', 'scheduled__2022-03-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', '/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py', '--cfg-path', '/var/folders/c5/lp6ccbfx3tq6qm5zscs07w980000gn/T/tmpk__v425x']
[2022-12-30T20:52:21.952-0500] {standard_task_runner.py:83} INFO - Job 105: Subtask Extract_n_Transform_Data
[2022-12-30T20:52:21.982-0500] {task_command.py:389} INFO - Running <TaskInstance: realtor_census_dashboard_etl.Extract_n_Transform_Data scheduled__2022-03-17T00:00:00+00:00 [running]> on host miguels-macbook-pro-2.local
[2022-12-30T20:52:22.022-0500] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=realtor_census_dashboard_etl
AIRFLOW_CTX_TASK_ID=Extract_n_Transform_Data
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T00:00:00+00:00
[2022-12-30T20:52:22.023-0500] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/c5/lp6ccbfx3tq6qm5zscs07w980000gn/T
[2022-12-30T20:52:22.023-0500] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'jupyter nbconvert --execute tranform_dfs.ipynb']
[2022-12-30T20:52:22.048-0500] {subprocess.py:86} INFO - Output:
[2022-12-30T20:52:22.586-0500] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 24349. PIDs of all processes in the group: [24350, 24349]
[2022-12-30T20:52:22.587-0500] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 24349
[2022-12-30T20:52:22.588-0500] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-30T20:52:22.588-0500] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-30T20:52:22.596-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-30T20:52:22.601-0500] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=realtor_census_dashboard_etl, task_id=Extract_n_Transform_Data, execution_date=20220317T000000, start_date=20221231T015221, end_date=20221231T015222
[2022-12-30T20:52:22.608-0500] {standard_task_runner.py:105} ERROR - Failed to execute job 105 for task Extract_n_Transform_Data (Task received SIGTERM signal; 24349)
[2022-12-30T20:52:22.619-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=24349, status='terminated', exitcode=1, started='20:52:21') (24349) terminated with exit code 1
[2022-12-30T20:52:22.620-0500] {process_utils.py:79} INFO - Process psutil.Process(pid=24350, status='terminated', started='20:52:22') (24350) terminated with exit code None
